### PR TITLE
added copyright

### PR DESCRIPTION
**Pull request by bgeye**
please verify, thank you!

### CODE REVIEW

**Review by bgeye2 — COMMENTED** [review]
are you sure that this change was ordered?

**Comment by bgeye** [comment]
hmmm okay let me check

**Comment by bgeye2** [comment]
for now it's ok, I will approve!
thanks for your effort!

**Review by bgeye2 — CHANGES_REQUESTED** [review]
why not in short?

**Comment by bgeye** [comment]
hmmm you're right I'll do

**Review by bgeye2 — APPROVED** [review]
perfect! wow this effort is incredible! love your work!

**Pull request merged**
